apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "pgsql://%s:%s@%s:%s/%s?charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
